### ISSUE TITLE
Wire up the arrow-dplyr-summarise tests on DuckDB engine

### ISSUE THREAD

**Issue by thisisnic** [voltrondata/substrait-r#87]

**Comment by thisisnic** [comment]
Hmm, this one somehow slipped through - this is already completed.

**Comment by amol-** [comment]
Yes, it now figures as completed on clickup too. 

As @thisisnic mentioned I think the problem was just that there were two tickets for the same task. 
This one was listed under https://github.com/voltrondata/substrait-r/issues/121 (so it was the one we were tracking) while https://github.com/voltrondata/substrait-r/pull/128 was the one where the work has actually happened but that we weren't tracking.
